import { BookingOption, Intent } from "./types";

// Welcome message
export const WELCOME_MESSAGE = `Hello! 👋 I'm **Sahara**, your AI assistant.

I can help you with:

• 🚌 **Bus Tickets** - Find and book bus rides
• ✈️ **Flights** - Search available flights
• 🏥 **Appointments** - Schedule doctor visits
• 🎬 **Movies** - Book cinema tickets

What would you like to do today?`;

// Quick action suggestions
export const QUICK_ACTIONS = [
    "Book a bus ticket",
    "Find flights",
    "Doctor appointment",
    "Movie tickets",
];

// Intent detection keywords
export const INTENT_KEYWORDS: Record<Intent, string[]> = {
    GREETING: ["hi", "hello", "hey", "good morning", "good evening", "namaste", "hola"],
    BUS_BOOKING: ["bus", "bus ticket", "travel by bus", "book bus", "bus to", "bus ride"],
    FLIGHT_BOOKING: ["flight", "fly", "airplane", "air ticket", "book flight", "flights to", "plane"],
    APPOINTMENT: ["appointment", "doctor", "hospital", "clinic", "checkup", "medical", "schedule"],
    MOVIE_BOOKING: ["movie", "cinema", "film", "theater", "show", "watch movie", "tickets"],
    GENERAL_QUERY: ["help", "what can you do", "services", "options", "menu", "back to menu"],
    UNKNOWN: [],
};

// Mock payment options
export const MOCK_PAYMENT_OPTIONS: BookingOption[] = [
    {
        id: "payment_qr",
        type: "payment_qr",
        title: "Scan & Pay Online (QR)",
        subtitle: "E-Sewa / Khalti / ConnectIPS",
        price: 0,
        currency: "NPR",
        details: { qr: "true" },
        available: true,
    },
    {
        id: "payment_cash",
        type: "payment_cash",
        title: "Pay after Service (On Visit)",
        subtitle: "Confirm reservation now, pay on visit",
        price: 0,
        currency: "NPR",
        details: { cash: "true" },
        available: true,
    },
];

// Mock bus options
export const MOCK_BUS_OPTIONS: BookingOption[] = [
    {
        id: "bus-1",
        type: "bus",
        title: "Deluxe Express",
        subtitle: "Kathmandu → Pokhara",
        price: 1200,
        currency: "NPR",
        details: {
            departure: "6:00 AM",
            duration: "7 hours",
            busType: "AC Deluxe",
            seats: "12 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-2",
        type: "bus",
        title: "Tourist Coach",
        subtitle: "Kathmandu → Pokhara",
        price: 1500,
        currency: "NPR",
        details: {
            departure: "7:30 AM",
            duration: "6.5 hours",
            busType: "Tourist Deluxe",
            seats: "8 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-3",
        type: "bus",
        title: "Night Sleeper",
        subtitle: "Kathmandu → Pokhara",
        price: 1800,
        currency: "NPR",
        details: {
            departure: "8:00 PM",
            duration: "8 hours",
            busType: "Sleeper Bus",
            seats: "5 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-4",
        type: "bus",
        title: "Greenline Travels",
        subtitle: "Kathmandu → Chitwan",
        price: 1400,
        currency: "NPR",
        details: {
            departure: "7:00 AM",
            duration: "6 hours",
            busType: "AC Sofa Seat",
            seats: "15 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-5",
        type: "bus",
        title: "Super Hiace",
        subtitle: "Kathmandu → Pokhara",
        price: 1000,
        currency: "NPR",
        details: {
            departure: "Every 30 mins",
            duration: "6 hours",
            busType: "Micro Bus",
            seats: "Available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-6",
        type: "bus",
        title: "Baba Adventure",
        subtitle: "Kathmandu → Chitwan",
        price: 1600,
        currency: "NPR",
        details: {
            departure: "6:30 AM",
            duration: "5 hours",
            busType: "VIP Sofa",
            seats: "10 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-7",
        type: "bus",
        title: "Swift Holidays",
        subtitle: "Kathmandu → Lumbini",
        price: 1800,
        currency: "NPR",
        details: {
            departure: "7:00 PM",
            duration: "9 hours",
            busType: "Super Deluxe",
            seats: "6 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-8",
        type: "bus",
        title: "East West Travels",
        subtitle: "Kathmandu → Kakarbhatta",
        price: 2200,
        currency: "NPR",
        details: {
            departure: "3:00 PM",
            duration: "14 hours",
            busType: "AC Deluxe",
            seats: "20 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-9",
        type: "bus",
        title: "Sajha Yatayat",
        subtitle: "Kathmandu → Baglung",
        price: 1300,
        currency: "NPR",
        details: {
            departure: "7:00 PM",
            duration: "10 hours",
            busType: "Standard",
            seats: "15 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
    {
        id: "bus-10",
        type: "bus",
        title: "Jagadamba Travels",
        subtitle: "Kathmandu → Biratnagar",
        price: 2000,
        currency: "NPR",
        details: {
            departure: "4:00 PM",
            duration: "12 hours",
            busType: "Deluxe",
            seats: "8 available",
        },
        available: true,
        venueId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    },
];

// Mock flight options
export const MOCK_FLIGHT_OPTIONS: BookingOption[] = [
    {
        id: "flight-1",
        type: "flight",
        title: "Buddha Air",
        subtitle: "Kathmandu → Pokhara",
        price: 4500,
        currency: "NPR",
        details: {
            departure: "8:00 AM",
            duration: "25 min",
            aircraft: "ATR 72-500",
            class: "Economy",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-2",
        type: "flight",
        title: "Yeti Airlines",
        subtitle: "Kathmandu → Pokhara",
        price: 4200,
        currency: "NPR",
        details: {
            departure: "10:30 AM",
            duration: "25 min",
            aircraft: "Jetstream 41",
            class: "Economy",
            seats: "5 left",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-3",
        type: "flight",
        title: "Shree Airlines",
        subtitle: "Kathmandu → Bhairahawa",
        price: 5200,
        currency: "NPR",
        details: {
            departure: "9:00 AM",
            duration: "35 min",
            aircraft: "Bombardier Q400",
            class: "Premium",
            seats: "Available",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-4",
        type: "flight",
        title: "Heli Services",
        subtitle: "Kathmandu → Everest Base Camp",
        price: 35000,
        currency: "NPR",
        details: {
            departure: "6:00 AM",
            duration: "3 hours",
            aircraft: "Airbus H125",
            class: "Charter",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-5",
        type: "flight",
        title: "Buddha Air",
        subtitle: "Kathmandu → Bharatpur",
        price: 3800,
        currency: "NPR",
        details: {
            departure: "11:00 AM",
            duration: "20 min",
            aircraft: "ATR 42",
            class: "Economy",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-6",
        type: "flight",
        title: "Yeti Airlines",
        subtitle: "Kathmandu → Biratnagar",
        price: 5500,
        currency: "NPR",
        details: {
            departure: "4:00 PM",
            duration: "40 min",
            aircraft: "ATR 72",
            class: "Economy",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-7",
        type: "flight",
        title: "Shree Airlines",
        subtitle: "Kathmandu → Nepalgunj",
        price: 6500,
        currency: "NPR",
        details: {
            departure: "3:30 PM",
            duration: "50 min",
            aircraft: "CRJ 200",
            class: "Economy",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-8",
        type: "flight",
        title: "Buddha Air",
        subtitle: "Kathmandu → Bhadrapur",
        price: 7200,
        currency: "NPR",
        details: {
            departure: "2:00 PM",
            duration: "45 min",
            aircraft: "ATR 72",
            class: "Economy",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
    {
        id: "flight-9",
        type: "flight",
        title: "Sita Air",
        subtitle: "Kathmandu → Lukla",
        price: 18000,
        currency: "NPR",
        details: {
            departure: "6:30 AM",
            duration: "30 min",
            aircraft: "Dornier 228",
            class: "Tourist",
        },
        available: true,
        venueId: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    },
];

// Mock appointment options
export const MOCK_APPOINTMENT_OPTIONS: BookingOption[] = [
    // Pediatricians
    {
        id: "apt-ped-1",
        type: "appointment",
        category: "pediatrician",
        title: "Dr. Suman Shrestha",
        subtitle: "Pediatrician - Child Specialist",
        price: 800,
        currency: "NPR",
        details: {
            hospital: "Apollo Clinic Kathmandu",
            address: "Kupondole, Lalitpur, Near Yala Maya Kendra",
            phone: "+977-1-5545678",
            experience: "12 years",
            nextSlot: "Tomorrow 10:00 AM",
            rating: "⭐ 4.9",
            specialization: "Child Health, Vaccination"
        },
        available: true,
    },
    {
        id: "apt-ped-2",
        type: "appointment",
        category: "pediatrician",
        title: "Dr. Anjali Pradhan",
        subtitle: "Pediatrician - Newborn Care",
        price: 1000,
        currency: "NPR",
        details: {
            hospital: "Grande International Hospital",
            address: "Dhapasi, Kathmandu, Near Ring Road",
            phone: "+977-1-4217766",
            experience: "18 years",
            nextSlot: "Today 3:00 PM",
            rating: "⭐ 5.0",
            specialization: "Newborn Care, Child Development"
        },
        available: true,
    },
    {
        id: "apt-ped-3",
        type: "appointment",
        category: "pediatrician",
        title: "Dr. Ramesh Khadka",
        subtitle: "Pediatrician - Child Health Expert",
        price: 700,
        currency: "NPR",
        details: {
            hospital: "CIWEC Hospital",
            address: "Lainchaur, Kathmandu, Near British Embassy",
            phone: "+977-1-4424111",
            experience: "10 years",
            nextSlot: "Tomorrow 2:00 PM",
            rating: "⭐ 4.7",
            specialization: "General Child Health, Fever Management"
        },
        available: true,
    },
    // Psychologists
    {
        id: "apt-psy-1",
        type: "appointment",
        category: "psychologist",
        title: "Dr. Priya Lama",
        subtitle: "Clinical Psychologist - Mental Health",
        price: 1500,
        currency: "NPR",
        details: {
            hospital: "Mind Care Nepal",
            address: "Jhamsikhel, Lalitpur, Near Jhamsikhel Chowk",
            phone: "+977-1-5547890",
            experience: "15 years",
            nextSlot: "Tomorrow 11:00 AM",
            rating: "⭐ 4.8",
            specialization: "Therapy, Counseling, Depression, Anxiety"
        },
        available: true,
    },
    {
        id: "apt-psy-2",
        type: "appointment",
        category: "psychologist",
        title: "Dr. Binod Maharjan",
        subtitle: "Psychologist - Cognitive Therapy",
        price: 1200,
        currency: "NPR",
        details: {
            hospital: "Sahara Counseling Center",
            address: "Baneshwor, Kathmandu, Near Minbhawan",
            phone: "+977-1-4781234",
            experience: "10 years",
            nextSlot: "Today 4:00 PM",
            rating: "⭐ 4.6",
            specialization: "CBT, Mental Health, Family Counseling"
        },
        available: true,
    },
    // General Physicians
    {
        id: "apt-1",
        type: "appointment",
        category: "general",
        title: "Dr. Sharma",
        subtitle: "General Physician",
        price: 500,
        currency: "NPR",
        details: {
            hospital: "City Hospital",
            address: "Thapathali, Kathmandu",
            phone: "+977-1-4240000",
            experience: "15 years",
            nextSlot: "Tomorrow 10:00 AM",
            rating: "⭐ 4.8",
        },
        available: true,
    },
    // Cardiologists
    {
        id: "apt-2",
        type: "appointment",
        category: "cardiologist",
        title: "Dr. Thapa",
        subtitle: "Cardiologist",
        price: 1500,
        currency: "NPR",
        details: {
            hospital: "Heart Care Center",
            address: "Maharajgunj, Kathmandu",
            phone: "+977-1-4412266",
            experience: "20 years",
            nextSlot: "Thursday 2:00 PM",
            rating: "⭐ 4.9",
        },
        available: true,
    },
    {
        id: "apt-urology",
        type: "appointment",
        category: "doctor",
        title: "Dr. Bikash Shrestha",
        subtitle: "Urologist",
        price: 1200,
        currency: "NPR",
        details: {
            hospital: "Grande International Hospital",
            experience: "12 years",
            nextSlot: "Wed 11:00 AM",
            rating: "⭐ 4.7",
            specialization: "Kidney & Urinary Tract",
        },
        available: true,
    },
    {
        id: "apt-nephro",
        type: "appointment",
        category: "doctor",
        title: "Dr. Pukar Chandra",
        subtitle: "Senior Nephrologist",
        price: 1800,
        currency: "NPR",
        details: {
            hospital: "Sahid Dharma Bhakta Centre",
            experience: "25 years",
            nextSlot: "Fri 9:00 AM",
            rating: "⭐ 5.0",
            specialization: "Kidney Transplant Expert",
        },
        available: true,
    },
    {
        id: "apt-gyno",
        type: "appointment",
        category: "doctor",
        title: "Dr. Sara Pradhan",
        subtitle: "Gynecologist",
        price: 1000,
        currency: "NPR",
        details: {
            hospital: "Paropakar Maternity",
            experience: "10 years",
            nextSlot: "Today 3:00 PM",
            rating: "⭐ 4.6",
        },
        available: true,
    },
    {
        id: "apt-3",
        type: "appointment",
        category: "doctor",
        title: "Dr. Rimal",
        subtitle: "Dentist",
        price: 800,
        currency: "NPR",
        details: {
            hospital: "Smile Clinic, Lazimpat",
            experience: "8 years",
            nextSlot: "Today 4:00 PM",
            rating: "⭐ 4.7",
        },
        available: true,
    },
    {
        id: "apt-4",
        type: "appointment",
        category: "doctor",
        title: "Dr. Karki",
        subtitle: "Dermatologist",
        price: 1200,
        currency: "NPR",
        details: {
            hospital: "Skin Care Center",
            experience: "12 years",
            nextSlot: "Friday 11:00 AM",
            rating: "⭐ 4.6",
        },
        available: true,
    },
    {
        id: "apt-5",
        type: "appointment",
        category: "college",
        title: "Presidential Business School",
        subtitle: "Expert Counseling Session",
        price: 0,
        currency: "NPR",
        details: {
            hospital: "Thapagaun, Baneshwor",
            experience: "PBS",
            nextSlot: "Daily 10AM - 4PM",
            rating: "⭐ 4.8",
        },
        available: true,
    },
    {
        id: "apt-6",
        type: "appointment",
        category: "college",
        title: "Islington College",
        subtitle: "Admission Inquiry",
        price: 0,
        currency: "NPR",
        details: {
            hospital: "Kamal Pokhari",
            experience: "IT & Business",
            nextSlot: "Walk-in Available",
            rating: "⭐ 4.7",
        },
        available: true,
    },
    {
        id: "svc-1",
        type: "appointment",
        category: "salon",
        title: "Glow & Style Salon",
        subtitle: "Haircut & Grooming",
        price: 500,
        currency: "NPR",
        details: {
            location: "New Baneshwor",
            specialist: "Rohan",
            nextSlot: "Today 2:00 PM",
            rating: "⭐ 4.5",
        },
        available: true,
    },
    {
        id: "svc-2",
        type: "appointment",
        category: "plumber",
        title: "Quick Fix Plumbing",
        subtitle: "Emergency Repairs",
        price: 800,
        currency: "NPR",
        details: {
            location: "On-site",
            specialist: "Hari Bahadur",
            responseTime: "1 Hour",
            rating: "⭐ 4.9",
        },
        available: true,
    },
    {
        id: "svc-3",
        type: "appointment",
        category: "electrician",
        title: "City Electric",
        subtitle: "Wiring & Installation",
        price: 1000,
        currency: "NPR",
        details: {
            location: "On-site",
            specialist: "Ram Kumar",
            responseTime: "2 Hours",
            rating: "⭐ 4.8",
        },
        available: true,
    },
    {
        id: "svc-4",
        type: "appointment",
        category: "makeup",
        title: "Glamour Studio",
        subtitle: "Party Makeup",
        price: 3500,
        currency: "NPR",
        details: {
            location: "Lazimpat",
            specialist: "Sita",
            nextSlot: "Tomorrow 8:00 AM",
            rating: "⭐ 5.0",
        },
        available: true,
    },
    {
        id: "svc-5",
        type: "appointment",
        category: "tailor",
        title: "Smart Fit Tailoring",
        subtitle: "Custom Suits",
        price: 8000,
        currency: "NPR",
        details: {
            location: "Putalisadak",
            specialist: "Master tailor",
            delivery: "4 Days",
            rating: "⭐ 4.7",
        },
        available: true,
    },
    {
        id: "svc-6",
        type: "appointment",
        category: "clinic",
        title: "Family Care Clinic",
        subtitle: "General Checkup",
        price: 400,
        currency: "NPR",
        details: {
            location: "Koteshwor",
            specialist: "Dr. Regmi",
            nextSlot: "Today 5:00 PM",
            rating: "⭐ 4.6",
        },
        available: true,
    },
];

// Mock movie options (Extended to include Events: Standup, Concerts, Plays)
export const MOCK_MOVIE_OPTIONS: BookingOption[] = [
    {
        id: "movie-1",
        type: "movie",
        category: "event",
        title: "Kabaddi 5",
        subtitle: "QFX Cinemas, Labim Mall",
        price: 400,
        currency: "NPR",
        details: {
            showtime: "4:30 PM",
            language: "Nepali",
            format: "2D",
            rating: "⭐ 4.5",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-4",
        type: "movie",
        category: "event",
        title: "Dune: Part Two",
        subtitle: "Big Movies, Kamalpokhari",
        price: 450,
        currency: "NPR",
        details: {
            showtime: "6:00 PM",
            language: "English",
            format: "2D",
            rating: "⭐ 4.7",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-5",
        type: "movie",
        category: "event",
        title: "Mahajatra",
        subtitle: "QFX Civil Mall",
        price: 400,
        currency: "NPR",
        details: {
            showtime: "3:00 PM",
            language: "Nepali",
            format: "2D",
            rating: "⭐ 4.6",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-6",
        type: "movie",
        category: "event",
        title: "Kung Fu Panda 4",
        subtitle: "One Cinemas, Baneshwor",
        price: 500,
        currency: "NPR",
        details: {
            showtime: "1:00 PM",
            language: "English",
            format: "3D",
            rating: "⭐ 4.5",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-7",
        type: "movie",
        category: "event",
        title: "Shaitaan",
        subtitle: "FCube Cinemas, Chabahil",
        price: 350,
        currency: "NPR",
        details: {
            showtime: "8:00 PM",
            language: "Hindi",
            format: "2D",
            rating: "⭐ 4.2",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-8",
        type: "movie",
        category: "event",
        title: "Godzilla x Kong",
        subtitle: "QFX Labim Mall",
        price: 550,
        currency: "NPR",
        details: {
            showtime: "5:30 PM",
            language: "English",
            format: "3D",
            rating: "⭐ 4.1",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-2",
        type: "movie",
        category: "event",
        title: "Avengers: Secret Wars",
        subtitle: "Big Movies, Civil Mall",
        price: 600,
        currency: "NPR",
        details: {
            showtime: "7:00 PM",
            language: "English",
            format: "3D IMAX",
            rating: "⭐ 4.8",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "movie-3",
        type: "movie",
        category: "event",
        title: "Pashupati Prasad 2",
        subtitle: "QFX Chhaya Center",
        price: 350,
        currency: "NPR",
        details: {
            showtime: "1:00 PM",
            language: "Nepali",
            format: "2D",
            rating: "⭐ 4.9",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "event-1",
        type: "movie",
        category: "standup",
        title: "Apoorwa Kshitiz Standup",
        subtitle: "Pragya Pratisthan, Kamaladi",
        price: 1500,
        currency: "NPR",
        details: {
            showtime: "Sat 4:00 PM",
            language: "Nepali",
            format: "Live Comedy",
            rating: "⭐ 4.9",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "event-2",
        type: "movie",
        category: "concert",
        title: "Nepathya Live in Kathmandu",
        subtitle: "Dasarath Rangasala Stadium",
        price: 2000,
        currency: "NPR",
        details: {
            showtime: "Fri 6:00 PM",
            language: "Nepali Rock",
            format: "Live Concert",
            rating: "⭐ 5.0",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "event-3",
        type: "movie",
        category: "drama",
        title: "Palpasa Cafe (Theatre Play)",
        subtitle: "Mandala Theatre, Anamnagar",
        price: 500,
        currency: "NPR",
        details: {
            showtime: "Daily 5:00 PM",
            language: "Nepali",
            format: "Drama",
            rating: "⭐ 4.7",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
    {
        id: "event-4",
        type: "movie",
        category: "dance",
        title: "Cultural Dance Night",
        subtitle: "Bhojan Griha, Dillibazar",
        price: 2500,
        currency: "NPR",
        details: {
            showtime: "7:00 PM",
            language: "Folk",
            format: "Dinner & Dance",
            rating: "⭐ 4.6",
        },
        available: true,
        venueId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    },
];

// Response templates (kept for reference but not heavily used now)
export const RESPONSE_TEMPLATES = {
    GREETING: "Hello! How can I assist you today?",
    BUS_BOOKING_START: "I'd be happy to help you book a bus ticket!",
    FLIGHT_BOOKING_START: "Great! Let's find you the perfect flight.",
    APPOINTMENT_START: "I can help you schedule an appointment.",
    MOVIE_BOOKING_START: "Let's get you some movie tickets!",
    OPTIONS_FOUND: "Here are the available options:",
    NO_OPTIONS: "I couldn't find any options matching your criteria.",
    BOOKING_COMPLETE: "Your booking is confirmed!",
    UNKNOWN: "I'm not sure I understood that. Could you please rephrase?",
};
